nombre=input('ingresa tu nombre:')
print('tu nombre es ', nombre)
grado=input('ingresa tu grado:')
print('tu grado es', grado)
grupo=input('ingresa tu grupo:')
print('tu grupo es el', grupo)
comida=input('ingresa tu comida:')
print('tu comida favorita es', comida)
mensaje=input('ingresa un mensaje')
print('el mensaje que te quieren enviar dice que', mensaje) 